name: MS Teams Notification

on: [issues]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action test
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        if: always() # to let this step always run even if previous step failed
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Issue created sucessfully
          notification-color: 17a2b8
          timezone: America/Denver
